CREATE DATABASE [Cadastro]
 CONTAINMENT = NONE
 GO
ALTER DATABASE [Cadastro] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Cadastro].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Cadastro] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Cadastro] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Cadastro] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Cadastro] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Cadastro] SET ARITHABORT OFF 
GO
ALTER DATABASE [Cadastro] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Cadastro] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Cadastro] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Cadastro] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Cadastro] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Cadastro] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Cadastro] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Cadastro] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Cadastro] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Cadastro] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Cadastro] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Cadastro] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Cadastro] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Cadastro] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Cadastro] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Cadastro] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Cadastro] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Cadastro] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Cadastro] SET  MULTI_USER 
GO
ALTER DATABASE [Cadastro] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Cadastro] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Cadastro] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Cadastro] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [Cadastro]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comprador](
	[CodigoId] [int] IDENTITY(1,1) NOT NULL,
	[NomeComprador] [nvarchar](100) NOT NULL
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Endereco](
	[CodigoId] [int] IDENTITY(1,1) NOT NULL,
	[Endereco] [nvarchar](100) NOT NULL
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Entradas](
	[CodigoId] [int] IDENTITY(1,1) NOT NULL,
	[DataImportacao] [datetime] NOT NULL,
	[CodigoComprador] [int] NOT NULL,
	[CodigoItem] [int] NOT NULL,
	[CodigoFornecedor] [int] NOT NULL,
	[CodigoEndereco] [int] NOT NULL,
	[Quantidade] [int] NOT NULL,
	[Valor] [int] NOT NULL
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Fornecedor](
	[CodigoId] [int] IDENTITY(1,1) NOT NULL,
	[NomeFornecedor] [nvarchar](100) NOT NULL
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Item](
	[CodigoId] [int] IDENTITY(1,1) NOT NULL,
	[DescricaoItem] [nvarchar](100) NOT NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Cadastro] SET  READ_WRITE 
GO
